[package]
name = "raumklang-core"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5"
ringbuf = "0.3.2"
rustfft = "6.0"
rand = { version = "0.8", features = ["std", "std_rng", "small_rng"] }
jack = "0.13.2"
thiserror = "2.0"
